name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '19'
          github-token: ${{ secrets.XPIPE_GITHUB_TOKEN }}

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Execute build
        run: ./gradlew clean build
